// Optional visual regression smoke test. Run with Playwright available in NODE_PATH.
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.join(__dirname,'..');
const server=http.createServer((req,res)=>{const target=path.join(root,req.url==='/'?'index.html':req.url);if(!target.startsWith(root+path.sep)){res.writeHead(403).end();return}fs.readFile(target,(err,data)=>{if(err){res.writeHead(404).end();return}res.setHeader('Content-Type',target.endsWith('.js')?'text/javascript':'text/html');res.end(data)})});
const bets=[
{id:'overlap-a',title:'Florida Gators @ Missouri Tigers',pick:'Over 55.5 Total',sport:'American Football',league:'ncaa',market:'Total',status:'pending',start:Date.parse('2026-10-01T15:30:00-04:00'),units:.62,odds:-128,ev:1.9,winPct:57.26,fv:-134,sharpOdds:'-148 / +121',gameLines:[{pick:'Over 55.5 Total',odds:-128,units:.62}],selectedGameLine:0,warnings:['Review headline odds'],raw:'Thu, Oct 01, 3:30 PM EDT\nOriginal QA signal'},
{id:'overlap-b',title:'Bayern Munich @ Olympiacos',pick:'Under 168.5 Total',sport:'Basketball',league:'Euroleague',market:'Total',status:'placed',start:Date.parse('2026-10-01T16:00:00-04:00'),units:1,odds:-110},
{id:'unknown',title:'Awaiting game time',pick:'Home team moneyline',status:'pending',start:null,hasTime:false},
{id:'night',title:'Dodgers @ Padres',pick:'Over 8.5 Total',sport:'Baseball',status:'placed',start:Date.parse('2026-10-02T23:00:00-04:00'),units:1,odds:105},
{id:'win',title:'Arsenal @ Chelsea',pick:'Arsenal Moneyline',sport:'Soccer',status:'won',start:Date.parse('2026-09-30T14:00:00-04:00'),units:1,odds:120},
{id:'loss',title:'Bruins @ Rangers',pick:'Rangers Moneyline (Regulation Time)',sport:'Hockey',status:'lost',start:Date.parse('2026-10-02T15:00:00-04:00'),units:.75,odds:-110}
].map(b=>({hasTime:true,lead:null,created:1,sentAt:Date.parse('2026-10-01T12:00:00-04:00'),...b}));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});try{
const context=await browser.newContext({viewport:{width:1400,height:1050},timezoneId:'America/New_York'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-10-01T14:00:00-04:00')});await page.addInitScript(data=>localStorage.setItem('rebet.v1',JSON.stringify(data)),{bets,settings:{lead:3,defaultOdds:-110,tz:'America/New_York'}});
await page.goto('http://127.0.0.1:'+server.address().port+'/dist/rebet.html');await page.getByRole('button',{name:'Calendar',exact:true}).click();
const first=page.locator('.timed[data-event="overlap-a"]');assert.equal(await first.evaluate(e=>e.style.top),'930px');assert.equal(await first.evaluate(e=>e.style.height),'210px');assert.notEqual(await first.evaluate(e=>e.style.left),await page.locator('.timed[data-event="overlap-b"]').evaluate(e=>e.style.left));assert.equal(await page.locator('.timed[data-event="night"]').count(),2);assert.equal(await page.locator('.timed[data-event="unknown"]').count(),0);assert.equal(await page.locator('.now-line').evaluate(e=>e.style.top),'840px');assert.equal(await page.locator('.place-pill[data-event="overlap-a"]').evaluate(e=>e.style.top),'750px');
await page.screenshot({path:path.join(__dirname,'screenshots/calendar-desktop.png'),fullPage:true,animations:'disabled'});
await first.click();assert.equal(await page.locator('#calDetail').evaluate(e=>e.open),true);await page.screenshot({path:path.join(__dirname,'screenshots/calendar-desktop-detail.png'),fullPage:true,animations:'disabled'});await page.locator('#calDetail').getByRole('button',{name:'Won',exact:true}).click();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Tracker',exact:true}).click();assert.match(await page.locator('#t-trk').innerText(),/Florida Gators/);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('rebet.v1')).bets.find(b=>b.id==='overlap-a').status),'won');
await page.getByRole('button',{name:'Calendar',exact:true}).click();await page.locator('#calView').selectOption('month');assert.equal(await page.locator('.month-grid .day').count(),42);await page.locator('#calView').selectOption('day');assert.equal(await page.locator('.time-column').count(),1);await page.getByRole('button',{name:'Next calendar period'}).click();assert.match(await page.locator('.time-head').innerText(),/Fri/);await page.getByRole('button',{name:'Today',exact:true}).click();await page.locator('#calView').selectOption('week');
await page.setViewportSize({width:390,height:844});await page.reload();await page.getByRole('button',{name:'Calendar',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.calendar-toolbar').scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollTo(0,document.querySelector('#t-cal').offsetTop));await page.screenshot({path:path.join(__dirname,'screenshots/calendar-phone.png'),fullPage:false,animations:'disabled'});await page.locator('.timed[data-event="overlap-a"]').click();await page.screenshot({path:path.join(__dirname,'screenshots/calendar-phone-detail.png'),fullPage:false,animations:'disabled'});await page.locator('#calDetail').getByRole('button',{name:'Edit',exact:true}).click();assert.equal(await page.locator('#dlg').evaluate(e=>e.open),true);await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.locator('.timed[data-event="overlap-a"]').click();await page.mouse.click(5,5);assert.equal(await page.locator('#calDetail').evaluate(e=>e.open),false);await page.locator('.timed[data-event="overlap-a"]').click();page.once('dialog',d=>d.accept());await page.locator('#detailDelete').click();assert.equal(await page.locator('[data-event="overlap-a"]').count(),0);await page.goto('file://'+path.join(root,'dist/rebet.html'));assert.equal(await page.getByRole('button',{name:'Calendar',exact:true}).count(),1);await page.getByRole('button',{name:'Calendar',exact:true}).click();assert.equal(await page.locator('.time-column').count(),7);assert.deepEqual(errors,[]);console.log('Calendar UI checks passed; four screenshots saved.');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
