const assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
const C=require('../calendar');
let n=0;function test(name,fn){fn();console.log('ok calendar: '+name);n++}
test('duration table and first-half estimates',()=>{for(const [sport,hours] of [['Baseball',3],['American Football',3.5],['Basketball',2.5],['Hockey',2.5],['Soccer',2],['Tennis',2],['Other',2.5]]){assert.equal(C.durationFor({sport}),hours*C.HOUR);assert.ok(C.durationFor({sport,marketDetail:'1st Half'})<=1.5*C.HOUR)}});
test('packing nested, chained, disjoint and touching intervals',()=>{const rows=C.pack([{top:60,bottom:240},{top:90,bottom:120},{top:120,bottom:180},{top:300,bottom:360}]);assert.deepEqual(rows.map(x=>[x.column,x.columns]),[[0,2],[1,2],[1,2],[0,1]]);for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++)if(rows[i].top<rows[j].bottom&&rows[j].top<rows[i].bottom)assert.notEqual(rows[i].column,rows[j].column)});
test('packing never mutates input',()=>{const rows=[{top:10,bottom:20}];C.pack(rows);assert.equal(rows[0].column,undefined)});
test('week and now line use civil dates',()=>{const d=new Date(2026,9,1,15,30);const w=C.weekRange(d);assert.equal(new Date(w.start).getDay(),1);assert.equal(w.days.length,7);assert.equal(C.nowPosition(+d,+d),930);assert.equal(C.nowPosition(+d,C.addDays(+d,1)),null);assert.equal(C.weekNumber(new Date(2021,0,1)),53)});
test('cross-midnight split and unknown-time omission',()=>{const day=+new Date(2026,9,1);const rows=C.segments([{id:'night',sport:'Baseball',start:+new Date(2026,9,1,23),hasTime:true},{id:'unknown',start:null,hasTime:false}],[day,C.addDays(day,1)]);assert.equal(rows.length,2);assert.deepEqual(rows.map(x=>[x.top,x.bottom]),[[1380,1440],[0,120]]);assert.ok(rows[0].continuesAfter&&rows[1].continuesBefore)});
test('New York DST weeks are 167/169 hours with seven civil days',()=>{const source=`const assert=require('node:assert/strict'),C=require('./calendar');for(const [month,date,hours] of [[2,8,167],[10,1,169]]){const w=C.weekRange(new Date(2026,month,date));assert.equal((w.end-w.start)/C.HOUR,hours);assert.ok(w.days.every(d=>new Date(d).getHours()===0));} const d=+new Date(2026,2,8);const s=C.segments([{sport:'Baseball',start:+new Date(2026,2,8,1,30),hasTime:true}],[d])[0];assert.equal(s.top,90);assert.equal(s.bottom,330);`;execFileSync(process.execPath,['-e',source],{cwd:require('node:path').join(__dirname,'..'),env:{...process.env,TZ:'America/New_York'}})});
console.log(n+' calendar checks passed');
