const assert=require('node:assert/strict'),S=require('../settlement'),C=require('../calendar');
let count=0;function test(name,fn){fn();count++;console.log('ok settlement: '+name)}
const bet=(extra={})=>({status:'pending',start:Date.parse('2026-10-01T19:30:00Z'),hasTime:true,sport:'American Football',...extra});
test('36 hours after whole-game end, including first-half picks',()=>{const b=bet({marketDetail:'1st Half',pick:'Over 4 (1st Half)'});assert.equal(S.deadline(b),b.start+39.5*C.HOUR);assert.equal(S.shouldLose(b,S.deadline(b)-1),false);assert.equal(S.shouldLose(b,S.deadline(b)),true)});
test('only unresolved known-time bets expire',()=>{for(const status of ['won','lost','push','skipped'])assert.equal(S.shouldLose(bet({status}),Infinity),false);for(const extra of [{start:null},{start:NaN},{start:'invalid'},{hasTime:false},{autoLossDisabled:true}])assert.equal(S.shouldLose(bet(extra),Infinity),false);assert.equal(S.shouldLose(bet({status:'placed'}),Infinity),true)});
test('expiry persists provenance, is idempotent, and allows late CASH correction',()=>{const b=bet(),now=S.deadline(b);assert.equal(S.apply([b],now),1);assert.equal(b.status,'lost');assert.equal(b.autoLossAt,now);assert.equal(S.apply([b],now+1),0);assert.equal(S.canMatchWin(b),true);S.confirmWin(b);assert.equal(b.status,'won');assert.equal(b.autoLossAt,undefined);assert.equal(S.apply([b],Infinity),0);assert.equal(S.canMatchWin(bet({status:'lost'})),false)});
test('placing keeps automation; reopening opts out and preserves manual outcomes',()=>{const b=bet();S.manualStatus(b,'placed');assert.equal(S.shouldLose(b,Infinity),true);S.apply([b],S.deadline(b));S.manualStatus(b,'pending');assert.equal(S.shouldLose(b,Infinity),false);S.manualStatus(b,'placed');assert.equal(S.shouldLose(b,Infinity),false);S.manualStatus(b,'lost');assert.equal(S.canMatchWin(b),false)});
test('grace uses elapsed hours across DST, independent of host timezone',()=>{const b=bet({start:Date.parse('2026-10-31T23:00:00-04:00'),sport:'Baseball'});assert.equal(S.deadline(b),Date.parse('2026-11-02T18:00:00Z'))});
console.log(count+' settlement checks passed');
